current time update improved.
mister-ben/videojs-seek-buttons pull request #68
Opened 2022-03-27 09:19 UTC by ghr-mohammadi

now + this.options_.seconds > totalDuration ? "replay not working" : "every thing is ok";

2022-03-27 09:23 UTC, ghr-mohammadi commented
now + this.options_.seconds > totalDuration ? "replay not working" : "every thing is ok";

2022-03-27 09:24 UTC, ghr-mohammadi commented
k

2022-03-30 19:50 UTC, mister-ben commented
Thanks. Makes sense, I just want to double check this plays nice with live streams.

2022-04-09 12:43 UTC, mister-ben requested changes
Thanks!. The suggested changes should make sure there's not an attempt to seek past the furthest point in live.

To fix the failing test, it will need a duration set here, e.g. `this.player.duration(100);`

https://github.com/mister-ben/videojs-seek-buttons/blob/d3de062daee9ebc9633a26343c647b1f80fd95a8/test/plugin.test.js#L90

2022-04-09 12:43 UTC, mister-ben commented on src/plugin.js
> +      this.player_.currentTime(Math.min(now + this.options_.seconds, totalDuration));
```suggestion
      let duration = this.player_.duration();

      if (this.player_.liveTracker && this.player_.liveTracker.isLive()) {
        duration = this.player_.liveTracker.seekableEnd();
      }

      this.player_.currentTime(Math.min(now + this.options_.seconds, duration));
```

2022-04-09 12:43 UTC, mister-ben commented on src/plugin.js
> +    const totalDuration = this.player_.duration();
```suggestion
```

2022-04-23 05:32 UTC, mister-ben commented
Thanks for the contribution, I've made a few updates.

2022-04-23 05:32 UTC, merged